name: 🐞 Bug Report
description: Report a reproducible problem in WebholeInk
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug.
        WebholeInk is intentionally minimal — please be precise.

  - type: input
    id: version
    attributes:
      label: WebholeInk Version
      placeholder: v0.1.0-core-stable
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: contracts
    attributes:
      label: Related contracts
      description: Reference CORE.md, ROUTES.md, CONTENT.md, etc.
